.travis.yml:
  forge_password: "WlwcEudP+OWXa4+NeCECmQ8IMp574174yzJokpmHvKkowqKhrsfa+tcFRc7ozf31ihDB60mThS9mOgIZfbU04qfKZ3TDTAIrIJCT74xuLUcILRj7juVNtfk95Ft4cGbTKOv9HJ0PXFkrbhpUdISILzopqS0CUAKjQVpPpoz5PJY="
